name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [2.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type-check
        run: deno check **/*.ts **/*.tsx

      - name: Run unit tests
        run: deno task test
        env:
          # Enable tests to run in CI environment
          CI: true

      - name: Run E2E tests
        run: |
          deno test --allow-net tests/e2e/basic.test.ts
          deno test --allow-net tests/e2e/migration-logic.test.ts
        env:
          # Configure test environment for CI
          AIRPORT_URL: http://localhost:8000
          TEST_LOG_LEVEL: info
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.x

      - name: Build application
        run: deno task build

      - name: Check build artifacts
        run: |
          if [ -d "_fresh" ]; then
            echo "Build completed successfully"
            ls -la _fresh/
          else
            echo "Build directory not found"
            exit 1
          fi
